//! Static vectors for the multi-step chained circuit, generated by
//! `circuits/convert_to_soroban.py` from a proof produced by
//! `circuits/setup.sh step_chain_statement`.
//!
//! # What these numbers are
//!
//! * `VK_HEX` is the 896-byte verification key of
//!   `circuits/step_chain_statement.circom`, serialized in the layout the
//!   Soroban verifier reads: `alpha(G1) || beta(G2) || gamma(G2) || delta(G2)
//!   || IC[0..6](G1)`. Six public inputs make it 896 bytes, not 768; the two
//!   circuits have different arities, which is why they have different keys and
//!   different storage slots.
//! * `PROOF_HEX` is the 256-byte Groth16 proof (`A` G1 64 B, `B` G2 128 B,
//!   `C` G1 64 B).
//! * `PUBLIC_INPUTS_HEX` are the six public signals in the order the circuit
//!   declares them: `[chain_start_root, chain_end_root, event_root, threshold,
//!   chain_length, domain_tag]`.
//!
//! # Why they are committed
//!
//! A verifier that never rejects anything is not a verifier. These vectors let
//! `cargo test` check, offline and inside the Soroban host, that the exact
//! encoding is accepted, that a mutated proof is refused, that reordered or
//! swapped public inputs are refused, and that a wrong-length key or proof is
//! refused before any decoding happens.
//!
//! The proof itself is a **local** proof: it was produced against a locally
//! generated powers-of-tau and a locally generated proving key. It is not a
//! receipt from a ceremony, and the README says so. What it does prove is that
//! the byte encoding and the verifier agree, which is what a regression test
//! needs.

//! Verifying key, proof and public inputs for the multi-step chained
//! circuit, serialized in the byte layout the Soroban verifier reads.
//! The contract tests replay exactly these bytes in the Soroban host.

pub const VK_HEX: &str = "218c0c7b0f6ab3f03af052bdf71acd7596ec7223e20657033a4175fa1a12052f0c4426e07662eb9f3b7fcea4f65dc2c54b3ca1d7d2f1b4f1f8ca8b74b4a4219d1f1f3f43c03f294d060476a64a919aec309660efa73baf8a04752d3904880fd31d7c0e2c2e50c0d69c049ab60f2e62832242f8f2bd488617e731c462da833aa31bdaf2c7568dcff0be7549ff6111273ba3bd48ab219815950d00d5b9c63f049e0021c105ac8175e9eb5a79d421944a3a25df73fddbf0e173091d7e8a331329e1198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c21800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa29a5372f79316c0614b8dbc1f32b13039e348b5787ce291e7cbbfe88beb7982c2b0c5f3401b9b4fc70f2a062f8e8e59b58556e28f0cd53d3f19815cfdce401190a12c0da22a51e18498a3e4fc18bd6263cbd7909d444eb1676ff521ed2c08ba5192cead20d3cc6e14ad251ed04a5dc5fb348657f0a8fd2c01843efb5c75f35550998e3c2c0a3bc92558546662b6e878914dcac6c6818baf658a63d9c8c9d9c6811b42b6365279cfa3931ae70527203f9993db68ad914dcefd09aa644ca845ee00ada2b019e3d46bb1b1ec1e1dca309679d21082ab83185554083bb20877b6ce10be79eeb1a4ad1cb70a574264252fd40c178a67346ae5949015bd4f8caa77e9a2d6c7f7eab1e9098134d90564875a408b1c686e5bc51c220322ba3b686ace02e2cc79dbfe205dcf3a17ca711c2dc6694f266a2ef471c74b5e2f809265a8c41ab022a93f3e14151bdcbb1b6f238ecce11bdb205d5cc0120bd1906b30389e4b452181463409b3f81686c3a103bbf65982d145fcd7afa984f4067f8985a62ee2c8b2ed98773a14121a95f3266561fd0ab2e2b0b12ce5ff9ddaa7c62d82a2fb7931d0dd36aad5e7089d1dba613288949b1d5743648c3168de8e9a6b7de0c1f5873a222d51e0fb192b193edd0192fe2ac938a7e229b7a95676011132b3d3c24b40e8b11e48f159dac555612497c4652d01f50b0b48a4f8cd63f33802968f16561f77f2216d9708d4d6899aea4c8a9b386174f8ac11a1384c2e845b94e1ff353eec8cd1cbfd1d74ccf782c2393127c15274a8c6b983a42ace76a2c67e658115dc7ceca";

pub const PROOF_HEX: &str = "1e85e245401c90b51c6bdf0a4e99043ad765c77594667bc82f28f5ff6c79647f1034df464d52dc435d58275226455ef3fa2bf8ab9215f4cb21cb2568ec73efad165e664ade2503a7c4771ba3ab91869f2864450713162c487c2b20967ba249452284cbe8640f3d0a7f673d44a2456437de54d66716fabf5a4dc5a7e41da441781a8c0d6658a5534458dea4da4894d1bf2144c2a75c39fd1a6becf1b4661ffcd4123d140d0ecfb8de6ddffe8443f91786382e6f78ae3dc8ef123f534012a90f5f114afa1896adf376c7c0cf8d02c9bf31ea28bd9a3035fe32888dc9a9dca6b0011db8be00ef01657d6c3e9b28fd44e22dc9bb26be5eda964957a14b9ece32b2a3";

pub const PUBLIC_INPUTS_HEX: [&str; 6] = [
    "121541d507c908ee36116665469848060f2725c9f9d0a0dae84f1ec2f206dc11",
    "15554df22066b7e6cba1dfcf561b0bd274bffc919da426ed68232862c1eedb58",
    "02192f60134be0544c47d75e5011cc80286874f2637fc93aaf4c0d46771ff81b",
    "0000000000000000000000000000000000000000000000000000000000000002",
    "0000000000000000000000000000000000000000000000000000000000000003",
    "009517e443e84062a6781b2a92160d0a325f4c5a45826a0c0b54644e2ed574f0",
];

/// Public signal order, so the contract test and this file cannot drift apart.
pub const PUBLIC_INPUT_ORDER: [&str; 6] = [
    "chain_start_root",
    "chain_end_root",
    "event_root",
    "threshold",
    "chain_length",
    "domain_tag",
];
