//! Canonical-pin reconciliation (K2 of the ZkZero regeneration design).
//!
//! "Repair" never patches torn bytes - it re-derives the stream from the
//! schema. The schema is pinned in independent places (the VM builder, the
//! boot slot schema, the canonical-set hash table, and the genesis
//! re-derivation), so a torn copy is regenerated by the copies that still
//! agree. This module is the reconciliation primitive: a strict majority
//! over the pin digests decides the agreed hash, a minority is reported as
//! torn (re-derivable from the schema), and a split with no strict majority
//! fails closed - the caller escalates to the highest alarm and never
//! guesses which side is right.

/// The number of independent pin sources the design carries.
pub const PIN_SOURCE_COUNT: usize = 4;

/// Outcome of reconciling the pin sources.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Reconciliation {
    /// Every source present agrees.
    Unanimous { hash: [u8; 32] },
    /// A strict majority agreed; the listed indices were torn and must be
    /// re-derived from the schema, which yields the agreed hash.
    Repaired { hash: [u8; 32], torn: Vec<usize> },
    /// No strict majority (for example a 2-2 split in four copies): fail
    /// closed, do not guess.
    Split,
}

/// Reconcile `pins` by strict majority. `pins` may be shorter than
/// [`PIN_SOURCE_COUNT`] while sources are still being wired in; the verdict
/// is over the sources actually present.
#[must_use]
pub fn reconcile(pins: &[[u8; 32]]) -> Reconciliation {
    if pins.is_empty() {
        return Reconciliation::Split;
    }
    // Count each distinct digest.
    let mut counts: Vec<([u8; 32], usize)> = Vec::new();
    for pin in pins {
        match counts.iter_mut().find(|(h, _)| h == pin) {
            Some((_, c)) => *c += 1,
            None => counts.push((*pin, 1)),
        }
    }
    counts.sort_by_key(|(_, c)| std::cmp::Reverse(*c));
    let (top, top_count) = counts[0];
    let n = pins.len();
    // Strict majority only: with four sources, 2-of-4 is not enough.
    if top_count * 2 <= n {
        return Reconciliation::Split;
    }
    let torn: Vec<usize> = pins
        .iter()
        .enumerate()
        .filter(|(_, p)| **p != top)
        .map(|(i, _)| i)
        .collect();
    if torn.is_empty() {
        Reconciliation::Unanimous { hash: top }
    } else {
        Reconciliation::Repaired { hash: top, torn }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canonical_set::{program_hash_of, CANONICAL_PROGRAM_HASHES};
    use zk_vm::private_transfer::build_private_transfer_check_program;

    fn pin(seed: u8) -> [u8; 32] {
        let mut p = [0u8; 32];
        p[0] = seed;
        p
    }

    fn parse_hex32(hex: &str) -> [u8; 32] {
        assert_eq!(hex.len(), 64, "pin hex must be 64 chars");
        let mut out = [0u8; 32];
        for i in 0..32 {
            out[i] = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("hex digit");
        }
        out
    }

    #[test]
    fn unanimous_sources_agree() {
        let a = pin(7);
        assert_eq!(
            reconcile(&[a, a, a, a]),
            Reconciliation::Unanimous { hash: a }
        );
    }

    #[test]
    fn single_torn_copy_is_repaired_by_majority() {
        let a = pin(1);
        let b = pin(2);
        assert_eq!(
            reconcile(&[a, a, a, b]),
            Reconciliation::Repaired {
                hash: a,
                torn: vec![3],
            }
        );
    }

    #[test]
    fn two_two_split_fails_closed() {
        let a = pin(1);
        let b = pin(2);
        assert_eq!(reconcile(&[a, a, b, b]), Reconciliation::Split);
    }

    #[test]
    fn no_strict_majority_fails_closed() {
        // 2-1-1: two copies agree but that is not a majority of four.
        let a = pin(1);
        let b = pin(2);
        let c = pin(3);
        assert_eq!(reconcile(&[a, a, b, c]), Reconciliation::Split);
    }

    #[test]
    fn empty_or_single_source() {
        assert_eq!(reconcile(&[]), Reconciliation::Split);
        let a = pin(9);
        assert_eq!(reconcile(&[a]), Reconciliation::Unanimous { hash: a });
    }

    /// The three live sources - the VM builder, the canonical-set hash table,
    /// and the boot slot attestation - must all derive the same digest. This
    /// is the fourth-derivation check running in code: any drift among the
    /// three is caught here, before genesis re-derivation exists.
    #[test]
    fn three_live_sources_reconcile_unanimously() {
        let from_builder =
            program_hash_of(&build_private_transfer_check_program().expect("builder must emit"));
        let from_hash_table = parse_hex32(CANONICAL_PROGRAM_HASHES[2]);
        let boot = crate::canonical_boot::check_canonical_programs().expect("boot attest");
        let entry = boot
            .iter()
            .find(|c| c.name == "private-transfer-check")
            .expect("boot carries the transfer entry");
        let from_boot = parse_hex32(&entry.hash_hex);

        assert_eq!(from_builder, from_hash_table, "builder vs hash table");
        assert_eq!(from_builder, from_boot, "builder vs boot slots");

        match reconcile(&[from_builder, from_hash_table, from_boot]) {
            Reconciliation::Unanimous { hash } => assert_eq!(hash, from_builder),
            other => panic!("the three live sources must be unanimous, got {other:?}"),
        }
    }
}
