//! The four-way Poseidon calibration, third and fourth leg: the Rust port
//! must reproduce witnesses computed by *circom's* Poseidon — the exact
//! `poseidon.circom` from the pinned circomlib that `circuits/gate_vm.circom`
//! includes. The fixtures in this directory are generated by
//! `circuits/gen_poseidon_probe.py` (docstring has the run order); they are
//! committed on purpose — a passing test must be reproducible from the repo
//! alone, and a golden file that only exists after someone regenerates it
//! pins nothing.
//!
//! This exists because hand-ported Poseidons fail silently. A wrong round
//! constant is not an error, it is just a different hash — and both the
//! Rust-side `program_root` and the circuit's fold would agree with
//! themselves while disagreeing with every proof the chain ever sees. The
//! probe short-circuits that entire class: if this test is green, the field,
//! the constants, the round schedule, and the circomlib version agree.

use gate_vm::field::Fp;
use gate_vm::poseidon::poseidon2;

#[test]
fn poseidon2_reproduces_the_circomlib_probe_witnesses() {
    let raw = include_str!("poseidon_golden.json");
    let fixtures: Vec<serde_json::Value> = serde_json::from_str(raw).expect("valid json");
    assert_eq!(fixtures.len(), 6, "probe count is pinned by the generator");
    for fx in &fixtures {
        let xs = (fx["x0"].as_str().unwrap(), fx["x1"].as_str().unwrap());
        let x0 = Fp::from_decimal(xs.0).unwrap();
        let x1 = Fp::from_decimal(xs.1).unwrap();
        let want = fx["out"].as_str().unwrap().to_string();
        let got = poseidon2(&x0, &x1);
        assert_eq!(
            got.to_decimal(),
            want,
            "poseidon2({}, {}) diverged from circom",
            xs.0,
            xs.1
        );
    }
}

#[test]
fn the_golden_files_are_not_the_generator_beating_its_own_bosom() {
    // (0,0) -> the well-known Goldilocks-free BN254 constant below only if
    // MDS+rounds match the published Poseidon test vector; it is asserted in
    // the circuit tests too, and here as the crate-visible tripwire.
    let raw = include_str!("poseidon_golden.json");
    let fixtures: Vec<serde_json::Value> = serde_json::from_str(raw).unwrap();
    let zero = fixtures
        .iter()
        .find(|fx| fx["x0"] == "0" && fx["x1"] == "0")
        .expect("probe (0,0) present");
    assert_eq!(
        zero["out"].as_str().unwrap(),
        "14744269619966411208579211824598458697587494354926760081771325075741142829156",
        "circomlib Poseidon(0,0) changed — the whole pinning chain is stale"
    );
}

#[test]
fn domain_tag_decimal_and_hex_are_one_value() {
    use gate_vm::witness::{DOMAIN_TAG_DEC, DOMAIN_TAG_HEX};
    let from_dec = Fp::from_decimal(DOMAIN_TAG_DEC).unwrap();
    assert_eq!(from_dec.to_hex64(), DOMAIN_TAG_HEX);
}
