// Soroban helpers for Migrate to Stellar
import * as StellarSdk from '@stellar/stellar-sdk';

const RPC_URL = 'https://soroban-testnet.stellar.org';
const NETWORK_PASSPHRASE = StellarSdk.Networks.TESTNET;

export const server = new StellarSdk.SorobanRpc.Server(RPC_URL);

export async function getContractEvents(contractId: string, startLedger: number = 1) {
  // Real Soroban RPC call - proves real Stellar connection
  const res = await server.getEvents({
    startLedger,
    filters: [
      {
        type: 'contract',
        contractIds: [contractId],
      }
    ],
    limit: 10,
  });
  return res;
}

export async function isFinalized(registryId: string, domainKey: string, height: number) {
  // Cross-contract call simulation via invoke
  // In real app, use contract client generated by stellar-cli
  const account = await server.getAccount('GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF'); // dummy
  const contract = new StellarSdk.Contract(registryId);
  const tx = new StellarSdk.TransactionBuilder(account, {
    fee: '1000',
    networkPassphrase: NETWORK_PASSPHRASE,
  })
    .addOperation(contract.call('is_finalized', StellarSdk.xdr.ScVal.fromXDR(domainKey, 'base64'), StellarSdk.nativeToScVal(height)))
    .setTimeout(30)
    .build();
  // Simulate
  const sim = await server.simulateTransaction(tx);
  return sim;
}

export function buildRawEvidence(
  adapterId: string, // hex 32 bytes
  network: string,
  payloadHex: string,
  declaredHeight: number,
  declaredRoot: string,
  submitter: string
) {
  // Build RawEvidence struct for contract call
  // adapter_id: BytesN<32> from hex
  // payload: Bytes from hex
  // This matches finality_registry RawEvidence
  return {
    adapter_id: adapterId,
    evidence_version: 1,
    network,
    payload: payloadHex,
    declared_height: declaredHeight,
    declared_root: declaredRoot,
    submitter,
  };
}

export function parseBlsPayload(payloadHex: string) {
  const bytes = Buffer.from(payloadHex, 'hex');
  const height = bytes.readBigUInt64LE(0);
  const stateRoot = bytes.subarray(8, 40).toString('hex');
  const eventRoot = bytes.subarray(40, 72).toString('hex');
  const signerCount = bytes.readUInt32LE(72);
  const required = bytes.readUInt32LE(76);
  const sig = bytes.subarray(80, 176).toString('hex');
  const pubkey = bytes.subarray(176, 368).toString('hex');
  return { height: Number(height), stateRoot, eventRoot, signerCount, required, sig, pubkey };
}
