#!/usr/bin/env python3
"""Extract the Poseidon(t=3) constants from the pinned circomlib and emit them
as a Rust source file.

The gate VM's hash opcode and the circom program-root fold must agree on every
round constant, or no trace will ever satisfy the circuit. Rather than copy
thousands of digits through a human, this script parses the very file the
compiler reads (node_modules/circomlib/circuits/poseidon_constants.circom) and
writes `crates/gate_vm/src/poseidon_consts.rs`. Re-running the generator and
diffing the output against the committed file is the drift check between the
Rust witness generator and the circom constraints.

Usage:
    python3 circuits/gen_poseidon3.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONSTS = os.path.join(ROOT, "node_modules/circomlib/circuits/poseidon_constants.circom")
OUT = os.path.join(ROOT, "crates/gate_vm/src/poseidon_consts.rs")


def function_body(text, fname):
    m = re.search(rf"function\s+{fname}\s*\(\s*t\s*\)\s*\{{", text)
    assert m, f"function {fname} not found"
    i = m.end()
    depth = 1
    while depth:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
        i += 1
    return text[m.end():i - 1]


def t3_block(body):
    """The `if (t==N)` cascade: return the bracketed arrays of the t==3 case."""
    m = re.search(r"t\s*==\s*3", body)
    assert m, "no t==3 case"
    start = body.index("[", m.end())
    depth = 0
    for i in range(start, len(body)):
        if body[i] == "[":
            depth += 1
        elif body[i] == "]":
            depth -= 1
            if depth == 0:
                return body[start:i + 1]
    raise SystemExit("unbalanced brackets in t==3 case")


def ints(block):
    return [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", block)]


def main():
    src = open(CONSTS).read()
    c3 = ints(t3_block(function_body(src, "POSEIDON_C")))
    s3 = ints(t3_block(function_body(src, "POSEIDON_S")))
    m3 = ints(t3_block(function_body(src, "POSEIDON_M")))
    p3 = ints(t3_block(function_body(src, "POSEIDON_P")))
    # Shape expectations for t=3: the PoseidonEx template indexes
    # N_ROUNDS_P[t-2], which for t=3 is 57 - not the 56 a reader of the
    # whitepaper tables would guess. The generator asserts the sizes the file
    # actually carries so a misread fails here rather than in a witness.
    assert len(c3) == 3 * 8 + 57 == 81, f"C3 len {len(c3)}"
    assert len(s3) == 57 * (2 * 3 - 1) == 285, f"S3 len {len(s3)}"
    assert len(m3) == 9 and len(p3) == 9, (len(m3), len(p3))

    def arr(name, values):
        out = [f"pub const {name}: [Fp; {len(values)}] = ["]
        out += [f'    Fp::from_hex("{v:064x}"),' for v in values]
        out += ["];", ""]
        return out

    lines = [
        "// @generated by circuits/gen_poseidon3.py -- do not edit by hand.",
        "//",
        "// Parse target: node_modules/circomlib/circuits/poseidon_constants.circom,",
        "// the pinned circomlib the circuits compile against. The shapes are the",
        "// ones the PoseidonEx template in poseidon.circom uses for t = 3",
        "// (8 full rounds, 56 partial rounds); the generator asserts them, so a",
        "// circomlib bump that changes the parameters fails loudly here instead",
        "// of silently desynchronising the witness from the constraints.",
        "",
        "use crate::field::Fp;",
        "",
    ]
    lines += arr("C", c3) + arr("S", s3) + arr("M", m3) + arr("P", p3)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {len(c3)} C, {len(s3)} S, {len(m3)} M, {len(p3)} P")


if __name__ == "__main__":
    sys.exit(main())
